# Generated by Django 3.2.9 on 2023-03-18 10:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productdetail',
            name='heading',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='servicedetail',
            name='heading',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
