# Generated by Django 3.2.9 on 2023-03-21 12:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0002_auto_20230318_1605'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Project',
            new_name='Portfolio',
        ),
    ]
