# Generated by Django 4.1.7 on 2023-03-14 13:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0003_blog_career_job_product_subscription_productdetail_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Information',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone', models.CharField(max_length=15)),
                ('phone_2', models.CharField(max_length=15)),
                ('branch', models.PositiveIntegerField(default=1)),
                ('projects', models.PositiveIntegerField(default=1)),
                ('clients', models.PositiveIntegerField(default=1)),
                ('members', models.PositiveIntegerField(default=1)),
                ('address', models.CharField(max_length=255)),
                ('email', models.URLField()),
                ('facebook', models.URLField()),
                ('twitter', models.URLField()),
                ('instagram', models.URLField()),
                ('linkedin', models.URLField()),
            ],
        ),
    ]
