# Generated by Django 3.2.9 on 2023-03-22 06:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0003_rename_project_portfolio'),
    ]

    operations = [
        migrations.AddField(
            model_name='information',
            name='whatsapp',
            field=models.URLField(default='wa.me/91123456789'),
            preserve_default=False,
        ),
    ]
