# Generated by Django 4.1.7 on 2023-03-15 11:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0008_blogdetail'),
    ]

    operations = [
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('category', models.CharField(choices=[('Testing', 'Testing'), ('Cleaning', 'Cleaning'), ('Repair', 'Repair'), ('Heating', 'Heating')], max_length=20)),
                ('image', models.ImageField(upload_to='projects')),
            ],
        ),
    ]
