# Generated by Django 4.1.7 on 2023-03-16 07:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0009_project'),
    ]

    operations = [
        migrations.CreateModel(
            name='Testimonial',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('photo', models.ImageField(upload_to='testimonial')),
                ('designation', models.CharField(max_length=255)),
                ('comment', models.TextField()),
            ],
        ),
        migrations.AlterField(
            model_name='career',
            name='email',
            field=models.EmailField(max_length=255),
        ),
    ]
