# Generated by Django 4.1.7 on 2023-03-17 10:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0013_blog_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='information',
            name='experience',
            field=models.PositiveIntegerField(default=1),
        ),
    ]
